## Python Basic Commands

In [2]:
# print
print("Fit a model")

Fit a model


In [3]:
print?

In [5]:
3+5 #addition

8

In [7]:
# concatenation

"Hello" + " "+"world"

'Hello world'

In [9]:
# Sequence which is list
x = [3,5,2]
x

[3, 5, 2]

In [10]:
y = [5,3,2]
y

[5, 3, 2]

In [11]:
x + y

[3, 5, 2, 5, 3, 2]

In [12]:
import numpy as np

In [13]:
x = np.array([3,5,2])
x

array([3, 5, 2])

In [15]:
y = np.array([3,5,7])
y

array([3, 5, 7])

In [16]:
x + y

array([ 6, 10,  9])

In [17]:
# 2 -dimensional array

x = np.array([[2,1],[3,5]])
x

array([[2, 1],
       [3, 5]])

In [21]:
x.ndim #check dimensional of array

2

In [22]:
x.dtype

dtype('int32')

In [23]:
np.array([[2.,3],[4,6]])

array([[2., 3.],
       [4., 6.]])

In [25]:
np.array([[2.,3],[4,6]]).dtype

dtype('float64')

In [27]:
x.shape

(2, 2)

In [28]:
# methods

x = np.array([1,2,4,5])
x.sum()

12

In [29]:
np.sum(x)

12

In [35]:
# reshape

x = np.array([[2.,3],[4,6],[3,7]])
x

array([[2., 3.],
       [4., 6.],
       [3., 7.]])

In [37]:
x.reshape((3,2))

array([[2., 3.],
       [4., 6.],
       [3., 7.]])

In [48]:
x = np.arange(6)
print("Before reshape: \n",x)
print("After reshape: \n", x.reshape(2,3))

Before reshape: 
 [0 1 2 3 4 5]
After reshape: 
 [[0 1 2]
 [3 4 5]]


In [49]:
x.reshape

<function ndarray.reshape>