## Python Basic Commands

In [3]:
# print
print("Fit a model")

Fit a model


In [4]:
print?

In [5]:
3+5 #addition

8

In [6]:
# concatenation

"Hello" + " "+"world"

'Hello world'

In [7]:
# Sequence which is list
x = [3,5,2]
x

[3, 5, 2]

In [8]:
y = [5,3,2]
y

[5, 3, 2]

In [9]:
x + y

[3, 5, 2, 5, 3, 2]

In [10]:
import numpy as np

In [11]:
x = np.array([3,5,2])
x

array([3, 5, 2])

In [12]:
y = np.array([3,5,7])
y

array([3, 5, 7])

In [13]:
x + y

array([ 6, 10,  9])

In [14]:
# 2 -dimensional array

x = np.array([[2,1],[3,5]])
x

array([[2, 1],
       [3, 5]])

In [15]:
x.ndim #check dimensional of array

2

In [16]:
x.dtype

dtype('int32')

In [17]:
np.array([[2.,3],[4,6]])

array([[2., 3.],
       [4., 6.]])

In [18]:
np.array([[2.,3],[4,6]]).dtype

dtype('float64')

In [19]:
x.shape

(2, 2)

In [20]:
# methods

x = np.array([1,2,4,5])
x.sum()

12

In [21]:
np.sum(x)

12

In [22]:
# reshape

x = np.array([[2.,3],[4,6],[3,7]])
x

array([[2., 3.],
       [4., 6.],
       [3., 7.]])

In [23]:
x.reshape((3,2))

array([[2., 3.],
       [4., 6.],
       [3., 7.]])

In [24]:
x = np.arange(6)
print("Before reshape: \n",x)
print("After reshape: \n", x.reshape(2,3))

Before reshape: 
 [0 1 2 3 4 5]
After reshape: 
 [[0 1 2]
 [3 4 5]]


In [25]:
x.reshape

<function ndarray.reshape>

In [26]:
# tuple
my_tuple = (3,4,5)
my_tuple

(3, 4, 5)

In [27]:
#can we modify tuple?
my_tuple[2] = 3

TypeError: 'tuple' object does not support item assignment

In [ ]:
x_reshape = x.reshape((3,2))
x_reshape

In [ ]:
x_reshape.T # Transpose

In [ ]:
np.sqrt(x)

In [ ]:
x**2

In [ ]:
x **0.5

In [ ]:
# Generate random normal variable N(0,1)

x = np.random.normal(size = 50)
x

In [ ]:
y = x + np.random.normal(loc = 50, scale = 1, size = 50)
y

In [ ]:
# Calculate the coeff between x and y 

np.corrcoef(x,y)

In [ ]:
# To get same result we can set random.seed using np.random.default_rng()
rng = np.random.default_rng(1303)
print(rng.normal(scale = 5, size = 2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale = 5, size = 2))


In [ ]:
# mean
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

In [ ]:
# variance
np.var(y), y.var(), np.mean((y - y.mean())**2)

In [ ]:
# Standard Deviation

np.std(y), np.sqrt(np.var(y))

In [ ]:
# matrix 

x = np.random.standard_normal((10,3))
x

In [ ]:
x.mean()

In [ ]:
x.mean(axis=0)

In [ ]:
##GRAPHICS

In [ ]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize= (8,8))
x = rng.standard_normal(10)
y = rng.standard_normal(10)
plt.plot(x,y)

In [ ]:
output = plt.subplots(figsize = (8,8))
fig = output[0]
ax = output[1]

In [ ]:
fig, ax = plt.subplots(figsize= (8,8))
plt.plot(x,y, 'o') # scatterplot

In [ ]:
fig, ax = plt.subplots(figsize= (8,8))
ax.scatter(x,y,marker = 'o');

In [ ]:
fig, ax = plt.subplots(figsize= (8,8))
ax.scatter(x,y,marker = 'o')
ax.set_title("This is x vs y plot")
ax.set_xlabel("This is x label")
ax.set_ylabel("This is y label");

In [ ]:
fig, ax = plt.subplots(figsize= (12,3)) # Change in size
ax.scatter(x,y,marker = 'o')
ax.set_title("This is x vs y plot")
ax.set_xlabel("This is x label")
ax.set_ylabel("This is y label");

In [ ]:
# multi-subplot 

fig, ax = plt.subplots(nrows=2, ncols=3, figsize = (12,3))


In [ ]:
fig, ax = plt.subplots(nrows=2, ncols=3, figsize = (12,3))
ax[0,1].plot(x,y, 'o')
ax[1,2].plot(x,y)

In [ ]:
# limit x axes 

ax[0,1].set_xlim([-1,1])
fig

In [ ]:
# 3d plot
fig, ax = plt.subplots(figsize= (8,8))
x = np.linspace(-np.pi, np.pi, 50)
y = x
f = np.multiply.outer(np.cos(y), 1 /(1+x**2))
ax.contour(x,y,f);

In [ ]:
fig, ax = plt.subplots(figsize= (8,8))
x = np.linspace(-np.pi, np.pi, 50)
y = x
f = np.multiply.outer(np.cos(y), 1 /(1+x**2))
ax.contour(x,y,f, levels = 45);

In [ ]:
fig, ax = plt.subplots(figsize= (8,8))
ax.imshow(f)

In [ ]:
# Create sequence 
x = np.arange(10)
x

In [ ]:
# slice 
"Hello World"[3:6]

In [ ]:
# Indexing Data 

x = np.arange(16).reshape((4,4))
x

In [ ]:
x[1,2] # Indexing start with 0 

In [ ]:
x[[1,3]] # fetch full row

In [ ]:
x[:,[0,2]]

In [ ]:
x[[1,3],[0,2]]

In [ ]:
x[[1,3],[0,2,3]]

In [ ]:
x[[1,3]][:,[0,2]]

In [ ]:
# Convenience function allow to extract matrix using mesh object. 
idx = np.ix_([1,3],[0,2,3])
x[idx]

In [30]:
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
x[1:4:2,0:3:2]

In [29]:
# Boolean Indexing
import numpy as np
keep_rows = np.zeros(x.shape[0], bool)
keep_rows

array([False, False, False, False, False, False])

In [33]:
keep_rows[[1,3]] = True
keep_rows

array([False,  True, False,  True, False, False])